1. Replace all odd numbers in arr with -1

Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


2. Stack arrays a and b vertically

Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:
#> array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [6]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html
np.concatenate([a, b], axis=0)

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html
np.vstack([a, b])

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.r_.html
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

3. Get the common items between a and b

Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
array([2, 4])

In [1]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.intersect1d.html
np.intersect1d(a,b)

array([2, 4])

4. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

In [7]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)

arr[:,[1, 2]] = arr[:,[2, 1]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


5. Print the full numpy array a without truncating.

Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
#> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
import numpy as np
np.set_printoptions(threshold=6)
a = np.arange(15)

np.set_printoptions(threshold=1000)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


6. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [81]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

i=0
for e in iris:
    if float(e[3])>1.0:
        print(e, i)
        break
    i+=1

#iris[:,3].astype(float)>1.0

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

[b'7.0' b'3.2' b'4.7' b'1.4' b'Iris-versicolor'] 50


array([50], dtype=int32)

7. Import the image from the following URL and convert it to a numpy array.

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [49]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
#im = PIL.Image.fromarray(np.uint8(arr))
#Image.Image.show(im)

[[[  9  72 125]
  [ 10  73 126]
  [ 11  74 127]
  ...
  [ 44 104 154]
  [ 44 104 154]
  [ 42 103 147]]

 [[ 10  73 126]
  [ 11  74 127]
  [ 12  75 128]
  ...
  [ 46 106 156]
  [ 46 106 156]
  [ 48 109 154]]

 [[ 11  74 127]
  [ 12  75 128]
  [ 13  76 129]
  ...
  [ 47 107 157]
  [ 47 107 157]
  [ 45 105 155]]

 ...

 [[ 15  28  36]
  [ 24  46  60]
  [ 16  33  43]
  ...
  [ 23  60  79]
  [ 39  73  98]
  [ 42  79 106]]

 [[ 32  50  60]
  [ 21  48  65]
  [ 27  49  62]
  ...
  [ 23  46  54]
  [ 22  41  56]
  [ 20  43  59]]

 [[ 29  55  68]
  [ 26  59  78]
  [ 19  48  64]
  ...
  [ 25  71  95]
  [ 34  75 107]
  [ 27  64  91]]]


8. Drop all nan values from a 1D numpy array

Input:
np.array([1,2,3,np.nan,5,6,7,np.nan])

Desired Output:
array([ 1.,  2.,  3.,  5.,  6.,  7.])

In [51]:
import numpy as np
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
# np.isnan(a)
a[~np.isnan(a)] # keep those records whose value is TRUE

[False False False  True False False False  True]


array([1., 2., 3., 5., 6., 7.])

9. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
arr = np.arange(15) 
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:
#> [[ 0  1  2  3] [ 2  3  4  5] [ 4  5  6  7] [ 6  7  8  9] [ 8  9 10 11] [10 11 12 13]]

In [93]:
def gen_strides(a, stride_len=5, window_len=5):
    # https://www.w3schools.com/python/python_operators.asp
    n_strides = ((a.size-window_len)//stride_len) + 1
    
    # DEBUG
    print(n_strides)
    for s in np.arange(0, n_strides*stride_len, stride_len):
        print(s, end=" ")
    print("")
    
    # e.g., np.array(a[a>2])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

arr = np.arange(15)
print(gen_strides(arr, stride_len=2, window_len=4))

6
0 2 4 6 8 10 
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


10. Create the ranks for the given numeric array a.

Input:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]

Desired output:
[4 2 6 0 8 7 9 3 5 1]

In [2]:
import numpy as np
np.random.seed(10)
a = np.random.randint(20, size=5)
print('Array: ', a)

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html
print(a.argsort())

Array:  [ 9  4 15  0 17]
[3 1 0 2 4]


In [3]:
print(a.argsort().argsort())

[2 1 3 0 4]
